feat: Recherche des arrêts par leur nom
arnoclr/panam pull request #5
Opened 2024-06-24 22:55 UTC by Leon-ED

Pour éviter de devoir aller chercher les coordonnées GPS depuis GMaps ou autre.
Rajoute un bouton qui ouvre une modale où on peut chercher un arrêt par son nom (se basant sur l'API de Wagon !).
<img width="1396" alt="image" src="https://github.com/arnoclr/panam/assets/93096590/cd651de0-c7b4-493c-a852-c45357343725">
Résultats : 
<img width="1396" alt="image" src="https://github.com/arnoclr/panam/assets/93096590/5d2d8b43-cd89-473e-bc46-711a5480282f">
Cliquer sur la ligne pour remplir les coordonnées de l'arrêt de la nom de la ligne sélectionné.
Pour les arrêts avec beaucoup de lignes : 
<img width="1396" alt="image" src="https://github.com/arnoclr/panam/assets/93096590/7bfc1a24-bdf9-4f5e-96f4-590be3415663">
On peut cliquer sur 'voir plus'
<img width="1396" alt="image" src="https://github.com/arnoclr/panam/assets/93096590/28bd6aae-2fa8-4613-93e5-113063a6819d">

2024-06-25 04:33 UTC, arnoclr requested changes
Quelques petits trucs à modif dans le code. J'ai pas pu tester encore mais jte fait confiance sur le fait que ça marche 🙂‍↕️

2024-06-25 04:33 UTC, arnoclr commented on src/services/Wagon.ts
> +  lines: string[]
Mettre SimpleLine ici

2024-06-25 04:33 UTC, arnoclr commented on src/services/Wagon.ts
> +  long: string
Mettre des number

2024-06-25 04:33 UTC, arnoclr commented on src/components/Stop.vue
> +            v-for="line in expandedGroups[mode] ? lines : lines.slice(0, 6)"
Mettre le 6 dans une constante dans le script en haut. Il est utilisé à 3 endroits

2024-06-25 04:33 UTC, arnoclr commented on src/components/Stop.vue
> +  lines: SimpleLine[]
Si l'objet stop contient directement les lignes, on a plus besoin de les envoyer séparément

2024-06-25 04:33 UTC, arnoclr commented on src/components/Stop.vue
> +    if (!isNaN(Number(a.id)) && !isNaN(Number(b.id))) {
Plutôt trier par rapport au numéro de ligne que l'ID non ?

2024-06-25 04:33 UTC, arnoclr commented on src/components/Stop.vue
> +function sortLines(lines: SimpleLine[]): SimpleLine[] {
Peut être bouger ce code dans un fichier utils/lines

2024-06-25 04:33 UTC, arnoclr commented on src/components/SearchModal.vue
> +  <div v-if="isOpen" class="backdrop" @click.self="closeDialog">
Que se passe t-il lorsqu'on appuie sur échap et qu'on tente de réouvrir le dialog ?

2024-06-25 08:47 UTC, Leon-ED commented on src/components/SearchModal.vue
> +  <div v-if="isOpen" class="backdrop" @click.self="closeDialog">
Ca la rouvre

2024-06-25 09:15 UTC, arnoclr requested changes
Presque nickel. Après tes modifs je testerai de mon côté.

2024-06-25 09:15 UTC, arnoclr commented on src/components/SearchModal.vue
> +  if (event.key === "Escape") {
J'avais pas vu mais ca serait mieux d'utiliser l'event natif https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close_event

2024-06-25 09:15 UTC, arnoclr commented on src/components/SearchModal.vue
> +  if (event.key === "Escape") {
En gros on écoute pas le clavier pour ensuite fermer le dialogue, mais on garde le comportement de base et on réagit quand le dialogue est fermé (de n'importe quelle manière)

2024-06-25 09:15 UTC, arnoclr commented on src/components/SearchModal.vue
> +})
Plus besoin de ca ducoup

2024-06-25 09:15 UTC, arnoclr commented on src/components/Stop.vue
> +    <button class="stop-name" @click="$emit('selected', stop.id, '')">
C'est peut etre mieux de renvoyer le stop en entier dans cet event plutôt que juste l'id

2024-06-25 09:15 UTC, arnoclr commented on src/components/Stop.vue
> +            @click="$emit('selected', stop.id, line.id)"
et la pareil renvoyer le stop entier et la ligne entière

2024-06-25 09:15 UTC, arnoclr commented on src/components/Stop.vue
> +            @click="$emit('selected', stop.id, line.id)"
SimpleStop, SimpleLine plutôt que string, string

2024-06-26 06:35 UTC, arnoclr requested changes

2024-06-26 06:35 UTC, arnoclr commented on src/services/Wagon.ts
> +    return "vite"
Je suis pas sur que ça continue de marcher sur je merge tel quel. C'est la clé d'api locale

2024-06-26 07:18 UTC, arnoclr approved these changes

2024-06-26 07:18 UTC, merged